const express = require('express');
const bodyParser = require('body-parser');
const cors = require('cors');
const admin = require('firebase-admin');

// Initialize firebase-admin with application default credentials when deployed.
try {
  admin.initializeApp();
} catch (e) {
  // In local dev this might be fine because the SDK auto-initializes differently.
  console.warn('Firebase admin initializeApp warning:', e.message || e);
}

const app = express();
app.use(cors());
app.use(bodyParser.json({ limit: '5mb' }));

// Middleware: verify Firebase ID token if present and populate req.user
async function verifyToken(req, res, next) {
  const authHeader = req.headers.authorization || '';
  if (!authHeader.startsWith('Bearer ')) return next();
  const idToken = authHeader.split('Bearer ')[1];
  try {
    const decoded = await admin.auth().verifyIdToken(idToken);
    req.user = decoded;
  } catch (err) {
    console.warn('Token verification failed:', err.message || err);
    return res.status(401).json({ error: 'Invalid auth token' });
  }
  return next();
}

app.post('/aiDesign', verifyToken, async (req, res) => {
  // Ensure caller is an admin
  const user = req.user;
  if (!user || !user.admin) {
    // Some setups use custom claims: { isAdmin: true } or { admin: true }. Support both.
    const isAdmin = (user && (user.admin || user.isAdmin || user.role === 'admin')) || false;
    if (!isAdmin) return res.status(403).json({ error: 'Admin privileges required' });
  }

  const { pageId, prompt, imageUrls = [], siteTheme } = req.body || {};
  if (!pageId || !prompt) return res.status(400).json({ error: 'pageId and prompt are required' });

  // If GEMINI is not configured via env, return a safe mock spec for local dev.
  const GEMINI_KEY = process.env.GEMINI_API_KEY || process.env.GOOGLE_API_KEY;
  if (!GEMINI_KEY) {
    console.warn('No Gemini API key configured — returning mock design spec.');
    const mock = {
      spec: {
        background_url: imageUrls[0] || 'https://picsum.photos/seed/ai_preview/1920/1080',
        headline: `AI-generated headline for ${pageId}`,
        subheadline: `Prompt summary: ${prompt.substring(0, 180)}`,
        buttons: [{ text: 'Learn More', link: '/', style: 'primary' }],
        layout: 'centered',
        classes: 'text-center py-20',
      },
      note: 'Mock spec generated by functions/aiDesign because GEMINI key is not set. Deploy with GEMINI configured for real results.'
    };
    return res.json(mock);
  }

  // Real Gemini integration placeholder: the server should call Gemini 2.5 Flash
  // using the Google Generative Models API with a strictly constrained prompt
  // and request JSON-only response. Implementing the full call requires
  // service account credentials and is intentionally left as an integration step.
  try {
    // If an API key or endpoint is provided, call the Generative Models REST API.
    const API_KEY = process.env.GENERATIVE_API_KEY || process.env.GEMINI_API_KEY || process.env.GOOGLE_API_KEY;
    const MODEL = process.env.GENERATIVE_MODEL || process.env.GEMINI_MODEL || 'models/gemini-2.5';

    if (API_KEY) {
      // Build a strict instruction to return only JSON matching our PageDesignSpec
      const instruction = `Return a JSON object matching this schema: { "background_url": string (optional), "headline": string, "subheadline": string (optional), "buttons": [{"text": string, "link": string (optional), "style": string (optional)}], "layout": string (optional), "classes": string (optional), "metadata": object (optional) }. Do NOT include any extra text. Respond with valid JSON only.`;

      const promptText = `${instruction}\n\nContext: siteTheme=${siteTheme || 'unknown'}. Admin prompt: ${prompt}\nReference image urls: ${imageUrls.join(', ')}`;

      // Use the Generative Models REST endpoint. The exact path/version may vary; adjust MODEL accordingly.
      const endpoint = `https://generativelanguage.googleapis.com/v1beta2/${MODEL}:generate?key=${API_KEY}`;

      const fetch = require('node-fetch');
      const body = {
        prompt: {
          text: promptText
        },
        temperature: 0.2,
        maxOutputTokens: 512
      };

      const aiResp = await fetch(endpoint, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(body)
      });

      if (!aiResp.ok) {
        const text = await aiResp.text();
        console.error('Generative API error:', aiResp.status, text);
        return res.status(502).json({ error: 'Generative API error', detail: text });
      }

      const aiJson = await aiResp.json();
      // The response structure may vary. Try to extract the text output.
      let rawOutput = '';
      if (aiJson.candidates && aiJson.candidates.length > 0) {
        rawOutput = aiJson.candidates[0].content || JSON.stringify(aiJson.candidates[0]);
      } else if (aiJson.output && aiJson.output[0] && aiJson.output[0].content) {
        rawOutput = aiJson.output[0].content;
      } else if (aiJson["responses"] && aiJson.responses[0] && aiJson.responses[0].content) {
        rawOutput = aiJson.responses[0].content;
      } else {
        rawOutput = JSON.stringify(aiJson);
      }

      // Attempt to parse JSON from the model output. Models may include trailing text; extract the first JSON object.
      const firstBrace = rawOutput.indexOf('{');
      const lastBrace = rawOutput.lastIndexOf('}');
      if (firstBrace !== -1 && lastBrace !== -1 && lastBrace > firstBrace) {
        const jsonText = rawOutput.slice(firstBrace, lastBrace + 1);
        try {
          const parsed = JSON.parse(jsonText);
          // Basic validation: must have headline or buttons
          if (!parsed.headline && !(parsed.buttons && parsed.buttons.length > 0)) {
            return res.status(502).json({ error: 'AI response missing required fields', raw: parsed });
          }
          return res.json({ spec: parsed });
        } catch (err) {
          console.error('Failed to parse AI JSON output:', err, 'rawOutput:', rawOutput);
          return res.status(502).json({ error: 'Failed to parse AI JSON output', rawOutput });
        }
      }

      return res.status(502).json({ error: 'AI returned no JSON', rawOutput });
    }

    // Fallback: return a simple structured spec if no API key is set.
    const spec = {
      background_url: imageUrls[0] || 'https://picsum.photos/seed/ai_live/1920/1080',
      headline: `AI (live) headline for ${pageId}`,
      subheadline: `Design generated with siteTheme=${siteTheme}`,
      buttons: [{ text: 'Primary CTA', link: '/', style: 'primary' }],
      layout: 'centered',
      classes: 'text-center py-20'
    };
    return res.json({ spec });
  } catch (err) {
    console.error('AI generation error:', err);
    return res.status(500).json({ error: 'AI generation failed' });
  }
});

// Health check
app.get('/health', (req, res) => res.json({ ok: true }));

// Export for Firebase Functions (if deployed using functions-framework / firebase functions)
module.exports = app;

// If run directly (node index.js), start an HTTP server for local testing
if (require.main === module) {
  const port = process.env.PORT || 5001;
  app.listen(port, () => console.log(`AI design function listening on http://localhost:${port}`));
}
/*
 HTTP Cloud Function: aiDesign
 - Verifies Firebase ID token and checks admin claim
 - Accepts { pageId, prompt, imageUrls, siteTheme }
 - If Gemini/Generative API not configured, returns a safe mock spec so frontend can continue
 - TODO: Integrate actual Gemini 2.5 Flash call server-side and return validated JSON spec
*/
const express = require('express');
const cors = require('cors');
const admin = require('firebase-admin');

// Initialize firebase-admin (will use GOOGLE_APPLICATION_CREDENTIALS in production)
try {
  admin.initializeApp();
} catch (e) {
  // ignore if already initialized
}

const app = express();
app.use(cors({ origin: true }));
app.use(express.json({ limit: '5mb' }));

// Helper: verify bearer token and check admin claim
async function verifyAdmin(req, res) {
  const authHeader = req.get('Authorization') || req.get('authorization');
  if (!authHeader || !authHeader.toLowerCase().startsWith('bearer ')) {
    res.status(401).json({ error: 'Missing Authorization Bearer token' });
    return null;
  }
  const idToken = authHeader.split(' ')[1];
  try {
    const decoded = await admin.auth().verifyIdToken(idToken);
    // Accept either custom claim 'admin' or uid in a configured list
    const isAdmin = decoded.admin === true || (decoded.claims && decoded.claims.admin === true) || decoded['isAdmin'] === true;
    if (!isAdmin) {
      res.status(403).json({ error: 'Requires admin privileges' });
      return null;
    }
    return decoded;
  } catch (err) {
    console.error('Token verify failed:', err);
    res.status(401).json({ error: 'Invalid or expired token' });
    return null;
  }
}

app.post('/aiDesign', async (req, res) => {
  const adminUser = await verifyAdmin(req, res);
  if (!adminUser) return;

  const { pageId, prompt, imageUrls = [], siteTheme } = req.body || {};
  if (!pageId || !prompt) return res.status(400).json({ error: 'pageId and prompt are required' });

  // If environment variable USE_MOCK_AI=true, return a deterministic mock spec
  if (process.env.USE_MOCK_AI === 'true' || !process.env.GEMINI_CONFIGURED) {
    const spec = {
      background_url: imageUrls[0] || 'https://picsum.photos/seed/waxi/1920/1080',
      headline: `${prompt.slice(0, 60)}...`,
      subheadline: `Generated for ${pageId} — theme: ${siteTheme || 'default'}`,
      buttons: [
        { text: 'Learn More', link: '/', style: 'primary' },
      ],
      layout: 'centered',
      classes: 'text-center',
      metadata: { generatedAt: new Date().toISOString(), generator: 'mock' }
    };
    return res.json({ spec });
  }

  // TODO: Integrate Gemini 2.5 Flash here. Example steps:
  // 1. Use Google Cloud service account credentials (already available via environment in Cloud Functions)
  // 2. Call the Generative Models REST API or use an official client library to request a JSON-only response
  // 3. Validate the returned JSON against the expected PageDesignSpec schema and return { spec }

  // Returning 501 with guidance so integrator can add the real call.
  return res.status(501).json({
    error: 'Gemini integration not configured on server. Set GEMINI_CONFIGURED=1 and implement the call in functions/index.js',
    hint: 'See README in /functions for deployment and Gemini integration guidance.'
  });
});

// Export for Cloud Functions
exports.app = app;

// Also allow running locally for testing
if (require.main === module) {
  const port = process.env.PORT || 8080;
  app.listen(port, () => console.log(`AI function listening on http://localhost:${port}`));
}
