import { Vehicle } from './types';
import { Page } from './App';

export const NAV_LINKS: { name: Page }[] = [
  { name: 'Home' },
  { name: 'Vehicles' },
  { name: 'Installment' },
  { name: 'Giveaway' },
  { name: 'About' },
  { name: 'Contact' },
];

export const VEHICLES: Vehicle[] = [
  {
    id: 1,
    name: 'BYD Seal',
    type: 'Sedan',
    price: 212800,
    description: 'A sleek, high-performance electric sedan with Ocean Aesthetics design.',
    imageUrl: 'https://picsum.photos/seed/bydseal/800/600',
    specs: [
      { icon: 'flash-outline', name: 'Range', value: '700km' },
      { icon: 'rocket-outline', name: '0-100km/h', value: '3.8s' },
      { icon: 'battery-charging-outline', name: 'Battery', value: '82.5 kWh' },
      { icon: 'speedometer-outline', name: 'Top Speed', value: '180 km/h' },
    ],
  },
  {
    id: 2,
    name: 'BYD Yuan Plus',
    type: 'SUV',
    price: 139800,
    description: 'A dynamic and energetic compact SUV, formerly known as Atto 3.',
    imageUrl: 'https://picsum.photos/seed/bydatto3/800/600',
    specs: [
      { icon: 'flash-outline', name: 'Range', value: '480km' },
      { icon: 'rocket-outline', name: '0-100km/h', value: '7.3s' },
      { icon: 'battery-charging-outline', name: 'Battery', value: '60.5 kWh' },
      { icon: 'speedometer-outline', name: 'Top Speed', value: '160 km/h' },
    ],
  },
  {
    id: 3,
    name: 'BYD Dolphin',
    type: 'Hatchback',
    price: 116800,
    description: 'An agile and stylish city car, perfect for urban adventures.',
    imageUrl: 'https://picsum.photos/seed/byddolphin/800/600',
    specs: [
      { icon: 'flash-outline', name: 'Range', value: '420km' },
      { icon: 'rocket-outline', name: '0-100km/h', value: '7.9s' },
      { icon: 'battery-charging-outline', name: 'Battery', value: '44.9 kWh' },
      { icon: 'speedometer-outline', name: 'Top Speed', value: '150 km/h' },
    ],
  },
  {
    id: 4,
    name: 'BYD Han EV',
    type: 'Sedan',
    price: 232800,
    description: 'A flagship luxury sedan that redefines performance and comfort.',
    imageUrl: 'https://picsum.photos/seed/bydhan/800/600',
    specs: [
      { icon: 'flash-outline', name: 'Range', value: '610km' },
      { icon: 'rocket-outline', name: '0-100km/h', value: '3.9s' },
      { icon: 'battery-charging-outline', name: 'Battery', value: '85.4 kWh' },
      { icon: 'speedometer-outline', name: 'Top Speed', value: '185 km/h' },
    ],
  },
  {
    id: 5,
    name: 'BYD Tang EV',
    type: 'SUV',
    price: 282800,
    description: 'A powerful and spacious 7-seater SUV for the whole family.',
    imageUrl: 'https://picsum.photos/seed/bydtang/800/600',
    specs: [
      { icon: 'flash-outline', name: 'Range', value: '505km' },
      { icon: 'rocket-outline', name: '0-100km/h', value: '4.4s' },
      { icon: 'battery-charging-outline', name: 'Battery', value: '86.4 kWh' },
      { icon: 'people-outline', name: 'Seating', value: '7' },
    ],
  },
  {
    id: 6,
    name: 'BYD Song Plus',
    type: 'SUV',
    price: 154800,
    description: 'A best-selling compact SUV known for its efficiency and style.',
    imageUrl: 'https://picsum.photos/seed/bydsong/800/600',
    specs: [
      { icon: 'flash-outline', name: 'Range', value: '505km' },
      { icon: 'rocket-outline', name: '0-100km/h', value: '8.5s' },
      { icon: 'battery-charging-outline', name: 'Battery', value: '71.7 kWh' },
      { icon: 'speedometer-outline', name: 'Top Speed', value: '175 km/h' },
    ],
  },
  {
    id: 7,
    name: 'BYD eBus',
    type: 'Commercial',
    price: 1800000,
    description: 'A reliable and zero-emission solution for public transportation.',
    imageUrl: 'https://picsum.photos/seed/bydebus/800/600',
    specs: [
      { icon: 'flash-outline', name: 'Range', value: '250km' },
      { icon: 'people-outline', name: 'Capacity', value: '90 passengers' },
      { icon: 'battery-charging-outline', name: 'Battery', value: '324 kWh' },
      { icon: 'speedometer-outline', name: 'Top Speed', value: '70 km/h' },
    ],
  },
  {
    id: 8,
    name: 'BYD eTruck',
    type: 'Commercial',
    price: 1200000,
    description: 'A powerful and efficient electric truck for logistics and heavy-duty tasks.',
    imageUrl: 'https://picsum.photos/seed/bydetruck/800/600',
    specs: [
      { icon: 'flash-outline', name: 'Range', value: '200km' },
      { icon: 'layers-outline', name: 'Payload', value: '25 tons' },
      { icon: 'battery-charging-outline', name: 'Battery', value: '177 kWh' },
      { icon: 'speedometer-outline', name: 'Top Speed', value: '85 km/h' },
    ],
  },
  {
    id: 9,
    name: 'Yangwang U8',
    type: 'Special',
    price: 1098000,
    description: 'A luxury off-road SUV with advanced technology, including tank turns and float mode.',
    imageUrl: 'https://picsum.photos/seed/bydu8/800/600',
    specs: [
      { icon: 'flash-outline', name: 'Range', value: '1000km' },
      { icon: 'rocket-outline', name: '0-100km/h', value: '3.6s' },
      { icon: 'power-outline', name: 'Horsepower', value: '1100 hp' },
      { icon: 'water-outline', name: 'Special', value: 'Amphibious' },
    ],
  },
];
